server:
  port: 8080
  servlet:
    context-path: /

spring:
  # todo 개발 데이터베이스 연결
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true # 콘솔창에 sql 출력
    properties:
      hibernate:
        format_sql: true # sql 예쁘게 출력
        default_batch_fetch_size: 500 # 일대다 컬렉션 조회 시 성능 최적화
    open-in-view: false # 영속성 컨텍스트 생존 범위를 트랜잭션 범위로 한정

  servlet:
    multipart:
      max-file-size: 10MB # 파일 업로드 요청 시 하나의 파일 크기 10MB로 제한 (default 1MB)
      max-request-size: 100MB # 파일 업로드 요청 시 모든 파일의 크기의합 100MB로 제한 (default 10MB)
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


logging:
  level:
    org.hibernate.type: trace # 콘솔창에 조건에 바인딩되는 값 및 조회 결과 출력
    com.app: debug # todo 패키지 수정

feign:
  client:
    config:
      default: # 전역적으로 세팅 할떄는 default에 설정한다.
        connectTimeout: 5000
        readTimeout: 5000

kakao:
  client:
    id: ENC(pxCRtuxEcR0W/JZesN8HpkiGaukOMXMmku/UIEOo6FP1A+GXSqLUZdPanTVEvLy0)
    secret: ENC(02QAYrwfqHMrOl9moL/klzR/c9hWR8d3GYbcCSPphXlx68+Jcj78hiVNQQoeLqgF)

token:
  secret: ENC(/by6BXjZrSxro8QjgEnWiFVj8pQ1Rz/22UZOSEFr5w+0GGjIv+n3nQ==) # 임의의 문자열
  access-token-expiration-time: 900000 # 15분 1000(ms) x 60(s) x 15(m)
  refresh-token-expiration-time: 1209600000 # 2주 1000(ms) x 60 (s) x 60(m) x 24(h) x 14(d)

jasypt:
  password: ${PASSWORD} # 암호화 할때 사용할 password